## LOAD and CLEAN DATASETS ##

### SMS DATASET ##

In [13]:
import pandas as  pd 

df_sms = pd.read_csv(r"C:\Users\shiv_\OneDrive\Desktop\AI-ScamShield\data\raw\spam.csv", encoding='latin-1')
df_sms.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [14]:
df_sms.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [15]:
df_sms.shape

(5572, 5)

In [16]:
df_sms.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [17]:
df_sms = df_sms[["v1", "v2"]]
df_sms.columns = ['label', 'message']

df_sms.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [18]:
df_sms['label'].value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

In [19]:
df_sms.isnull().sum()

label      0
message    0
dtype: int64

In [ ]:
df_sms.duplicated().sum()

np.int64(403)

In [20]:
df_sms = df_sms.drop_duplicates()
df_sms.shape

(5169, 2)

In [21]:
df_sms.to_csv(r'../data/processed/sms_clean.csv', index=False)

### Phishing Email Dataset ###

In [22]:
df_phish = pd.read_csv(r'../data/raw/Phishing_Email.csv')
df_phish.head()

,Unnamed: 0,Email Text,Email Type
0,0,"re : 6 . 1100 , disc : uniformitarianism , re ...",Safe Email
1,1,the other side of * galicismos * * galicismo *...,Safe Email
2,2,re : equistar deal tickets are you still avail...,Safe Email
3,3,\nHello I am your hot lil horny toy.\n I am...,Phishing Email
4,4,software at incredibly low prices ( 86 % lower...,Phishing Email

In [23]:
df_phish.info()
df_phish.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18650 entries, 0 to 18649
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  18650 non-null  int64
 1   Email Text  18634 non-null  object
 2   Email Type  18650 non-null  object
dtypes: int64(1), object(2)
memory usage: 437.2+ KB

Index(['Unnamed: 0', 'Email Text', 'Email Type'], dtype='object')

In [24]:
df_phish.shape

(18650, 3)

In [25]:
df_phish = df_phish.drop(columns=['Unnamed: 0'], axis=1)
df_phish.columns = ['message', 'label']
df_phish.head()

                                             message           label
0  re : 6 . 1100 , disc : uniformitarianism , re ...      Safe Email
1  the other side of * galicismos * * galicismo *...      Safe Email
2  re : equistar deal tickets are you still avail...      Safe Email
3  \nHello I am your hot lil horny toy.\n    I am...  Phishing Email
4  software at incredibly low prices ( 86 % lower...  Phishing Email

In [26]:
df_phish.isnull().sum()

message    16
label       0
dtype: int64

In [27]:
df_phish = df_phish.dropna()
df_phish.shape

(18634, 2)

In [28]:
df_phish['label'].value_counts()

label
Safe Email        11322
Phishing Email     7312
Name: count, dtype: int64

In [29]:
df_phish.duplicated().sum()

np.int64(1096)

In [30]:
df_phish = df_phish.drop_duplicates()
df_phish.shape

(17538, 2)

In [31]:
df_phish.to_csv(r'../data/processed/phishing_email_clean.csv', index=False)

### Fraud Email Dataset ###

In [32]:
import pandas as pd
df_fraud = pd.read_csv(r"C:\Users\shiv_\OneDrive\Desktop\AI-ScamShield\data\raw\fraud_email_.csv")
df_fraud.head()

                                                Text  Class
0  Supply Quality China's EXCLUSIVE dimensions at...      1
1                         over. SidLet me know. Thx.      0
2  Dear Friend,Greetings to you.I wish to accost ...      1
3  MR. CHEUNG PUIHANG SENG BANK LTD.DES VOEUX RD....      1
4          Not a surprising assessment from Embassy.      0

In [33]:
df_fraud.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11929 entries, 0 to 11928
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Text    11928 non-null  object
 1   Class   11929 non-null  int64
dtypes: int64(1), object(1)
memory usage: 186.5+ KB

In [34]:
df_fraud.shape

(11929, 2)

In [35]:
df_fraud.columns

Index(['Text', 'Class'], dtype='object')

In [36]:
df_fraud.columns = ['message', 'label']
df_fraud.head(10)

                                             message  label
0  Supply Quality China's EXCLUSIVE dimensions at...      1
1                         over. SidLet me know. Thx.      0
2  Dear Friend,Greetings to you.I wish to accost ...      1
3  MR. CHEUNG PUIHANG SENG BANK LTD.DES VOEUX RD....      1
4          Not a surprising assessment from Embassy.      0
5  Monica -Huma Abedin <Huma@clintonemail.com>Tue...      0
6  Pis print.H <hrod17@clintonemail.com>Thursday ...      0
7  Dear Tom--H <hrod17@clintonemail.com>Friday De...      0
8  Greetings from barrister Robert Williams=2CDea...      1
9  FYI. Thanks again for signing the book ---- an...      0

In [37]:
df_fraud.isnull().sum()

message    1
label      0
dtype: int64

In [38]:
df_fraud['label'].value_counts()

label
0    6742
1    5187
Name: count, dtype: int64

In [39]:
df_fraud.duplicated().sum()

np.int64(1679)

In [40]:
df_fraud = df_fraud.dropna()
df_fraud = df_fraud.drop_duplicates()
df_fraud.shape

(10249, 2)

In [41]:
df_fraud.to_csv(r'../data/processed/fraud_email_clean.csv', index=False)

### Fake Job Posting Dataset ###

In [42]:
df_jobs = pd.read_csv(r"C:\Users\shiv_\OneDrive\Desktop\AI-ScamShield\data\raw\Fake_Jobs_Postings.csv")
df_jobs.head()

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0

In [43]:
df_jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17880 entries, 0 to 17879
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_id               17880 non-null  int64
 1   title                17880 non-null  object
 2   location             17534 non-null  object
 3   department           6333 non-null   object
 4   salary_range         2868 non-null   object
 5   company_profile      14572 non-null  object
 6   description          17879 non-null  object
 7   requirements         15184 non-null  object
 8   benefits             10668 non-null  object
 9   telecommuting        17880 non-null  int64
 10  has_company_logo     17880 non-null  int64
 11  has_questions        17880 non-null  int64
 12  employment_type      14409 non-null  object
 13  required_experience  10830 non-null  object
 14  required_education   9775 non-null   object
 15  industry             12977 non-null  object
 16  function             11425 non-null  object
 17  fraudulent           17880 non-null  int64
dtypes: int64(5), object(13)
memory usage: 2.5+ MB

In [44]:
df_jobs.shape

(17880, 18)

In [45]:
df_jobs.columns

Index(['job_id', 'title', 'location', 'department', 'salary_range',
       'company_profile', 'description', 'requirements', 'benefits',
       'telecommuting', 'has_company_logo', 'has_questions', 'employment_type',
       'required_experience', 'required_education', 'industry', 'function',
       'fraudulent'],
      dtype='object')

In [46]:
df_jobs['fraudulent'].value_counts()

fraudulent
0    17014
1      866
Name: count, dtype: int64

In [47]:
text_cols = ['title', 'company_profile', 'description', 'requirements', 'benefits']

for col in text_cols:
    df_jobs[col] = df_jobs[col].fillna('')

In [48]:
df_jobs['message'] = (
    df_jobs['title'] + ' ' +
    df_jobs['company_profile'] + ' ' +
    df_jobs['description'] + ' ' +
    df_jobs['requirements'] + ' ' +
    df_jobs['benefits']
)

df_jobs[['message', 'fraudulent']].head()

                                             message  fraudulent
0  Marketing Intern We're Food52, and we've creat...           0
1  Customer Service - Cloud Video Production 90 S...           0
2  Commissioning Machinery Assistant (CMA) Valor ...           0
3  Account Executive - Washington DC Our passion ...           0
4  Bill Review Manager SpotSource Solutions LLC i...           0

In [49]:
df_jobs = df_jobs[['message', 'fraudulent']]
df_jobs.columns = ['message', 'label']

df_jobs['label'] = df_jobs['label'].map({0: 'legit', 1: 'scam'})

df_jobs.head()

                                             message  label
0  Marketing Intern We're Food52, and we've creat...  legit
1  Customer Service - Cloud Video Production 90 S...  legit
2  Commissioning Machinery Assistant (CMA) Valor ...  legit
3  Account Executive - Washington DC Our passion ...  legit
4  Bill Review Manager SpotSource Solutions LLC i...  legit

In [50]:
df_jobs.duplicated().sum()

np.int64(1814)

In [51]:
df_jobs = df_jobs.drop_duplicates()

In [52]:
df_jobs.to_csv(r'../data/processed/job_postings_clean.csv', index=False)
df_jobs.shape

(16066, 2)

### Fixing labels of datasets ###

In [53]:
df_sms = pd.read_csv(r"C:\Users\shiv_\OneDrive\Desktop\AI-ScamShield\data\processed\sms_clean.csv")
df_sms['label'] = df_sms['label'].map({'ham': 'legit', 'spam': 'scam'})
df_sms.to_csv(r'../data/processed/sms_clean.csv', index=False)
df_sms['label'].value_counts()

label
legit    4516
scam      653
Name: count, dtype: int64

In [54]:
df_phish = pd.read_csv(r"C:\Users\shiv_\OneDrive\Desktop\AI-ScamShield\data\processed\phishing_email_clean.csv")
df_phish['label'] = df_phish['label'].map({'Safe Email': 'legit', 'Phishing Email': 'scam'})
df_phish.to_csv('../data/processed/phishing_email_clean.csv', index=False)
df_phish['label'].value_counts()

label
legit    10980
scam      6558
Name: count, dtype: int64

In [55]:
df_fraud = pd.read_csv(r"C:\Users\shiv_\OneDrive\Desktop\AI-ScamShield\data\processed\fraud_email_clean.csv")
df_fraud['label'] = df_fraud['label'].map({0: 'legit', 1: 'scam'})
df_fraud.to_csv('../data/processed/fraud_email_clean.csv', index=False)
df_fraud['label'].value_counts()

label
legit    5915
scam     4334
Name: count, dtype: int64

In [56]:
df_sms['source'] = 'sms'
df_phish['source'] = 'phishing_email'
df_fraud['source'] = 'fraud_email'
df_jobs['source'] = 'job_posting'

### Define Scam Category ###

In [57]:
scam_keywords = {
    'lottery': ['lottery', 'won', 'winner', 'prize', 'congratulations', 'claim your', 'jackpot'],
    'banking_kyc': ['kyc', 'account will be blocked', 'account suspended', 'update your account', 'bank account', 'debit card', 'credit card blocked', 'verify your account'],
    'phishing': ['click here', 'verify your account', 'login to your', 'confirm your identity', 'suspicious activity', 'security alert'],
    'job_scam': ['work from home', 'earn $', 'no experience required', 'hiring now', 'job offer', 'per week', 'easy money'],
    'investment': ['investment opportunity', 'guaranteed returns', 'double your money', 'crypto', 'bitcoin', 'trading profit', 'forex'],
    'upi_payment': ['upi', 'google pay', 'phonepe', 'paytm', 'refund', 'payment failed', 'transaction failed'],
    'tech_support': ['virus detected', 'your computer', 'microsoft support', 'tech support', 'call this number immediately', 'system infected'],
    'digital_arrest': ['digital arrest', 'police', 'cbi', 'court notice', 'legal action', 'arrest warrant', 'customs department', 'income tax department']
}

In [58]:
def assign_scam_type(text):
    text = str(text).lower()
    for category, keywords in scam_keywords.items():
        for kw in keywords:
            if kw in text:
                return category
    return 'unknown'

In [59]:
df_sms['scam_type'] = df_sms.apply(
    lambda row: assign_scam_type(row['message']) if row['label'] == 'scam' else 'none',
    axis=1
)

df_sms['scam_type'].value_counts()

scam_type
none              4516
unknown            517
lottery            126
job_scam             7
phishing             1
upi_payment          1
digital_arrest       1
Name: count, dtype: int64

In [60]:
df_phish = pd.read_csv(r'../data/processed/phishing_email_clean.csv')
df_phish['scam_type'] = df_phish['label'].apply(lambda x: 'phishing' if x == 'scam' else 'none')
df_phish['scam_type'].value_counts()

scam_type
none        10980
phishing     6558
Name: count, dtype: int64

In [61]:
df_jobs2 = pd.read_csv('../data/processed/job_postings_clean.csv')
df_jobs2['scam_type'] = df_jobs2['label'].apply(lambda x: 'job_scam' if x == 'scam' else 'none')
df_jobs2['scam_type'].value_counts()

scam_type
none        15348
job_scam      718
Name: count, dtype: int64

In [62]:
df_fraud = pd.read_csv('../data/processed/fraud_email_clean.csv')
df_fraud['scam_type'] = df_fraud.apply(
    lambda row: assign_scam_type(row['message']) if row['label'] == 'scam' else 'none',
    axis=1
)
df_fraud['scam_type'].value_counts()

scam_type
none              5915
unknown           2985
banking_kyc       1012
lottery            193
digital_arrest      71
investment          27
upi_payment         25
phishing            16
job_scam             5
Name: count, dtype: int64

In [ ]:
df_phish.to_csv('../data/processed/phishing_email_clean.csv', index=False)
df_jobs.to_csv('../data/processed/job_postings_clean.csv', index=False)
df_fraud.to_csv('../data/processed/fraud_email_clean.csv', index=False)
df_sms.to_csv('../data/processed/sms_clean.csv', index=False)

In [64]:
df_sms['source'] = 'sms'
df_phish['source'] = 'phishing_email'
df_fraud['source'] = 'fraud_email'
df_jobs2['source'] = 'job_posting'

master_df = pd.concat([df_sms, df_phish, df_fraud, df_jobs2], ignore_index=True)
master_df.shape

(49022, 4)

In [65]:
master_df['label'].value_counts()

label
legit    36759
scam     12263
Name: count, dtype: int64

In [66]:
master_df['scam_type'].value_counts()

scam_type
none              36759
phishing           6575
unknown            3502
banking_kyc        1012
job_scam            730
lottery             319
digital_arrest       72
investment           27
upi_payment          26
Name: count, dtype: int64

In [67]:
master_df.isnull().sum()

label        0
message      0
source       0
scam_type    0
dtype: int64

In [68]:
master_df.duplicated(subset=['message']).sum()

np.int64(3)

In [69]:
master_df = master_df.drop_duplicates(subset=['message'])
master_df.shape

(49019, 4)

In [70]:
master_df.to_csv('../data/processed/master_dataset.csv', index=False)