## LOAD and CLEAN DATASETS ##

### SMS DATASET ##

In [1]:
import pandas as  pd 

df = pd.read_csv(r"C:\Users\shiv_\OneDrive\Desktop\AI-ScamShield\data\raw\spam.csv", encoding='latin-1')
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [3]:
df.shape

(5572, 5)

In [4]:
df.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [5]:
df = df[["v1", "v2"]]
df.columns = ['label', 'message']

df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
df['label'].value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

In [7]:
df.isnull().sum()

label      0
message    0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(403)

In [9]:
df = df.drop_duplicates()
df.shape

(5169, 2)

In [10]:
df.to_csv(r'../data/processed/sms_clean.csv', index=False)

### Phishing Email Dataset ###

In [11]:
df_phish = pd.read_csv(r'../data/raw/Phishing_Email.csv')
df_phish.head()

,Unnamed: 0,Email Text,Email Type
0,0,"re : 6 . 1100 , disc : uniformitarianism , re ...",Safe Email
1,1,the other side of * galicismos * * galicismo *...,Safe Email
2,2,re : equistar deal tickets are you still avail...,Safe Email
3,3,\nHello I am your hot lil horny toy.\n I am...,Phishing Email
4,4,software at incredibly low prices ( 86 % lower...,Phishing Email

In [13]:
df_phish.info()
df_phish.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18650 entries, 0 to 18649
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  18650 non-null  int64
 1   Email Text  18634 non-null  object
 2   Email Type  18650 non-null  object
dtypes: int64(1), object(2)
memory usage: 437.2+ KB

Index(['Unnamed: 0', 'Email Text', 'Email Type'], dtype='object')

In [14]:
df_phish.shape

(18650, 3)

In [15]:
df_phish = df_phish.drop(columns=['Unnamed: 0'], axis=1)
df_phish.columns = ['message', 'label']
df_phish.head()

                                             message           label
0  re : 6 . 1100 , disc : uniformitarianism , re ...      Safe Email
1  the other side of * galicismos * * galicismo *...      Safe Email
2  re : equistar deal tickets are you still avail...      Safe Email
3  \nHello I am your hot lil horny toy.\n    I am...  Phishing Email
4  software at incredibly low prices ( 86 % lower...  Phishing Email

In [16]:
df_phish.isnull().sum()

message    16
label       0
dtype: int64

In [19]:
df_phish = df_phish.dropna()
df_phish.shape

(18634, 2)

In [20]:
df_phish['label'].value_counts()

label
Safe Email        11322
Phishing Email     7312
Name: count, dtype: int64

In [21]:
df_phish.duplicated().sum()

np.int64(1096)

In [22]:
df_phish = df_phish.drop_duplicates()
df_phish.shape

(17538, 2)

In [23]:
df_phish.to_csv(r'../data/processed/phishing_email_clean.csv', index=False)